version: '3.8'

services:
  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    user: "${UID:-1000}:${GID:-1000}"

  moatless-api:
    image: aorwall/moatless-tools-api:latest
    command: api
    volumes:
      - ${MOATLESS_DIR:-./moatless}:/data/moatless
      - /var/run/docker.sock:/var/run/docker.sock
      - ${MOATLESS_SOURCE_DIR:-/dev/null}:/app/moatless
      - ${MOATLESS_COMPONENTS_PATH:-/dev/null}:/opt/components
      - ${CUSTOM_REQUIREMENTS_PATH:-./custom_requirements.txt}:/app/custom_requirements.txt
    environment:
      - REDIS_URL=redis://redis:6379
      - MOATLESS_DIR=/data/moatless
      - MOATLESS_COMPONENTS_PATH=/opt/components
      - WORKERS_COUNT=1
      - WORKERS=1
      - PYTHONPATH=/app
      - MOATLESS_RUNNER=docker
      - MOATLESS_STORAGE=file
      - MOATLESS_HOST_DIR=${MOATLESS_DIR:-./data/moatless}
      
      - MOATLESS_HOST_RUNNER_SOURCE_DIR=${MOATLESS_SOURCE_DIR}
      - MOATLESS_HOST_COMPONENTS_PATH=${MOATLESS_COMPONENTS_PATH}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - VOYAGE_API_KEY=${VOYAGE_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - MOATLESS_AUTH_ENABLED=${MOATLESS_AUTH_ENABLED}
    depends_on:
      redis:
        condition: service_healthy

  moatless-ui:
    image: aorwall/moatless-ui:latest
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - VITE_API_BASE_URL=http://moatless-api:8000/api
    depends_on:
      - moatless-api

volumes:
  redis-data:
