version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    user: "${UID:-1000}:${GID:-1000}"

  api:
    image: ${DOCKER_IMAGE:-aorwall/moatless-tools:latest}
    build:
      context: .
      dockerfile: Dockerfile
    command: api
    ports:
      - "8000:8000"
    volumes:
      - ${MOATLESS_DIR:-./data/moatless}:/data/moatless
      - ${MOATLESS_REPO_DIR:-./data/repos}:/data/repos
      - ${INDEX_STORE_DIR:-./data/index_stores}:/data/index_stores
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - REDIS_URL=redis://redis:6379
      - MOATLESS_DIR=/data/moatless
      - MOATLESS_REPO_DIR=/data/repos
      - INDEX_STORE_DIR=/data/index_stores
      # Pass all environment variables from .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - VOYAGE_API_KEY=${VOYAGE_API_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AZURE_API_KEY=${AZURE_API_KEY}
      - AZURE_API_BASE=${AZURE_API_BASE}
      - AZURE_API_VERSION=${AZURE_API_VERSION}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_HOST=${LANGFUSE_HOST}
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING}
      - TESTBED_API_KEY=${TESTBED_API_KEY}
      - TESTBED_BASE_URL=${TESTBED_BASE_URL}
      - DEFAULT_MODEL=${DEFAULT_MODEL}
      - CHEAP_MODEL=${CHEAP_MODEL}
    depends_on:
      redis:
        condition: service_healthy

  worker:
    image: ${DOCKER_IMAGE:-aorwall/moatless-tools:latest}
    build:
      context: .
      dockerfile: Dockerfile
    command: worker
    volumes:
      - ${MOATLESS_DIR:-./data/moatless}:/data/moatless
      - ${MOATLESS_REPO_DIR:-./data/repos}:/data/repos
      - ${INDEX_STORE_DIR:-./data/index_stores}:/data/index_stores
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - REDIS_URL=redis://redis:6379
      - MOATLESS_DIR=/data/moatless
      - MOATLESS_REPO_DIR=/data/repos
      - INDEX_STORE_DIR=/data/index_stores
      # Pass all environment variables from .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - VOYAGE_API_KEY=${VOYAGE_API_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AZURE_API_KEY=${AZURE_API_KEY}
      - AZURE_API_BASE=${AZURE_API_BASE}
      - AZURE_API_VERSION=${AZURE_API_VERSION}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_HOST=${LANGFUSE_HOST}
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING}
      - TESTBED_API_KEY=${TESTBED_API_KEY}
      - TESTBED_BASE_URL=${TESTBED_BASE_URL}
      - DEFAULT_MODEL=${DEFAULT_MODEL}
      - CHEAP_MODEL=${CHEAP_MODEL}
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      replicas: ${WORKER_COUNT:-1}

volumes:
  redis-data:
